#Postgresql Configuration
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d7d12dq8qa3s73bdgtr0-a.singapore-postgres.render.com/moneymanager_wv2r
spring.datasource.username=moneymanager_wv2r_user
spring.datasource.password=hwj9lZ2JuEFfGNg7vmI15CgNXUcBhKSt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
