#Postgresql Configuration
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d84933n7f7vs739sojq0-a.singapore-postgres.render.com/moneymanager_cx7t
spring.datasource.username=moneymanager_cx7t_user
spring.datasource.password=pcImGuDdGzox0Jn2W7hhMyxi8biz9y3E
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
